import React, { useRef } from 'react';
import { useGLTF, Html } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';
import { ViewType } from './SpaceshipScene';

interface EnduranceModelProps {
  activeView: ViewType;
}

export function EnduranceModel({ activeView, ...props }: EnduranceModelProps) {
  // Use generic type assertion since we don't have the exact types generated by gltfjsx
  const { scene } = useGLTF('/images/interstellar__endurance.glb') as any;
  const group = useRef<THREE.Group>(null);

  // Slow rotation for cinematic effect
  useFrame((state) => {
    if (group.current) {
      // Gentle floating animation
      group.current.position.y = Math.sin(state.clock.elapsedTime * 0.2) * 0.1;
      
      // Auto-rotate based on view would be handled by OrbitControls, 
      // but we can add subtle movement here if needed
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      {/* The primitive object will handle the nested scene structure of the GLB */}
      {/* Reverted scale to 0.04 as requested */}
      <primitive object={scene} scale={0.04} />
      
      {/* Telemetry Annotations - Conditionally rendered based on activeView */}
      
      {/* ENGINE VIEW */}
      {(activeView === 'overview' || activeView === 'engines') && (
        <Html position={[5, 0, 0]} distanceFactor={10} className="pointer-events-none z-0">
          <div className={`bg-black/80 backdrop-blur-md border border-hologram-green/50 p-3 rounded-lg w-48 shadow-[0_0_15px_rgba(16,185,129,0.3)] transform transition-all duration-500 ${activeView === 'engines' ? 'scale-110 border-hologram-green' : 'scale-100 opacity-70'} pointer-events-auto cursor-help`}>
            <div className="flex justify-between items-center mb-1">
              <span className="text-hologram-green font-bold font-orbitron text-xs">MAIN THRUSTERS</span>
              <span className="w-2 h-2 rounded-full bg-hologram-green animate-pulse"></span>
            </div>
            <div className="text-white font-rajdhani text-sm">STATUS: OPERATIONAL</div>
            <div className="h-px bg-hologram-green/30 my-2 w-full"/>
            <div className="font-mono text-xs text-blue-300">OUTPUT: 98.4%</div>
            <div className="font-mono text-xs text-blue-300">TEMP: 420K</div>
            {activeView === 'engines' && (
              <>
                 <div className="font-mono text-xs text-blue-300">FUEL FLOW: 450 kg/s</div>
                 <div className="font-mono text-xs text-warning-orange">VECTOR: NORM</div>
              </>
            )}
            {/* Connecting Line */}
            <div className="absolute top-1/2 -left-8 w-8 h-px bg-hologram-green/50 origin-right rotate-12"></div>
          </div>
        </Html>
      )}

      {/* LIFE SUPPORT VIEW */}
      {(activeView === 'overview' || activeView === 'life-support') && (
        <Html position={[-3.5, 2.5, 0]} distanceFactor={10} className="pointer-events-none z-0">
          <div className={`bg-black/80 backdrop-blur-md border border-blue-400/50 p-3 rounded-lg w-48 shadow-[0_0_15px_rgba(96,165,250,0.3)] transform transition-all duration-500 ${activeView === 'life-support' ? 'scale-110 border-blue-400' : 'scale-100 opacity-70'}`}>
            <div className="flex justify-between items-center mb-1">
              <span className="text-blue-400 font-bold font-orbitron text-xs">HABITAT RING</span>
              <span className="w-2 h-2 rounded-full bg-blue-400 animate-pulse"></span>
            </div>
            <div className="text-white font-rajdhani text-sm">LIFE SUPPORT: ACTIVE</div>
            <div className="h-px bg-blue-400/30 my-2 w-full"/>
            <div className="flex justify-between text-xs font-mono text-gray-300">
              <span>O2</span>
              <span>98%</span>
            </div>
            <div className="flex justify-between text-xs font-mono text-gray-300">
              <span>PRESS</span>
              <span>101.3 kPa</span>
            </div>
             {activeView === 'life-support' && (
              <>
                 <div className="flex justify-between text-xs font-mono text-gray-300">
                  <span>TEMP</span>
                  <span>21.5°C</span>
                </div>
                 <div className="flex justify-between text-xs font-mono text-gray-300">
                  <span>HUMIDITY</span>
                  <span>45%</span>
                </div>
              </>
            )}
             {/* Connecting Line */}
             <div className="absolute top-1/2 -right-8 w-8 h-px bg-blue-400/50"></div>
          </div>
        </Html>
      )}
      
      {/* COMMS VIEW */}
       {(activeView === 'overview' || activeView === 'comms') && (
         <Html position={[0, -1, 3]} distanceFactor={10} className="pointer-events-none z-0">
          <div className={`bg-black/80 backdrop-blur-md border border-orange-400/50 p-3 rounded-lg w-48 shadow-[0_0_15px_rgba(251,146,60,0.3)] transform transition-all duration-500 ${activeView === 'comms' ? 'scale-110 border-orange-400' : 'scale-100 opacity-70'}`}>
            <div className="flex justify-between items-center mb-1">
              <span className="text-orange-400 font-bold font-orbitron text-xs">COMMS ARRAY</span>
              <span className="w-2 h-2 rounded-full bg-orange-400 animate-pulse"></span>
            </div>
            <div className="text-white font-rajdhani text-sm">SIGNAL: STRONG</div>
            <div className="h-px bg-orange-400/30 my-2 w-full"/>
            <div className="font-mono text-xs text-gray-300">Last Ping: 0.04s</div>
            <div className="font-mono text-xs text-gray-300">Encryption: AES-4096</div>
             {activeView === 'comms' && (
              <>
                 <div className="font-mono text-xs text-gray-300">BANDWIDTH: 450 TB/s</div>
                 <div className="font-mono text-xs text-hologram-green">UPLINK: SECURE</div>
              </>
            )}
            <div className="absolute -top-8 left-1/2 h-8 w-px bg-orange-400/50"></div>
          </div>
        </Html>
       )}

       {/* GRAVITY VIEW (New) */}
       {activeView === 'gravity' && (
         <Html position={[0, 0, 0]} distanceFactor={10} className="pointer-events-none z-0">
          <div className="bg-black/80 backdrop-blur-md border border-purple-500/50 p-3 rounded-lg w-48 shadow-[0_0_15px_rgba(168,85,247,0.3)] animate-pulse">
            <div className="flex justify-between items-center mb-1">
              <span className="text-purple-500 font-bold font-orbitron text-xs">GRAVITY DRIVE</span>
              <span className="w-2 h-2 rounded-full bg-purple-500 animate-pulse"></span>
            </div>
            <div className="text-white font-rajdhani text-sm">SPIN RATE: 5 RPM</div>
            <div className="h-px bg-purple-500/30 my-2 w-full"/>
            <div className="font-mono text-xs text-gray-300">G-FORCE: 1.0 G</div>
            <div className="font-mono text-xs text-gray-300">STABILITY: 99.9%</div>
            <div className="absolute -bottom-8 left-1/2 h-8 w-px bg-purple-500/50"></div>
          </div>
        </Html>
       )}
    </group>
  );
}

useGLTF.preload('/images/interstellar__endurance.glb');
